server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

